# Creates a Drupal web app with MySQL database
# Usage: docker-compose up -d
version: '2'
services:
  # PHP and Apache.
  php:
    image: nodespark/php:7.2-apache
    volumes:
    - ./docker/apache/sites-enabled/default.conf:/etc/apache2/sites-enabled/000-default.conf
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./docker/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    - ~/.ssh:/root/.ssh
    volumes_from:
    - drush_volumed
    - core
    ports:
    - "80:80"
    - "25"
    links:
    - mysql
    - mailhog
    - elastic
  core:
    image: cweagans/bg-sync
    volumes:
    - ./:/source
    - /var/www
    environment:
    - SYNC_DESTINATION=/var/www
    - SYNC_MAX_INOTIFY_WATCHES=40000
    - SYNC_VERBOSE=1
    privileged: true
  memcached:
    image: memcached
    ports:
    - "11211:11211"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
    - "5601:5601"
    links:
      - elastic
  mysql:
    image: mysql:5.6
    hostname: localhost
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drip
      - MYSQL_PASSWORD=drop
  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    ports:
      - "8026:8025"
      - "1026"
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: drip
      PMA_PASSWORD: drop
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8081:80"
  drush_volumed:
    image: nodespark/drush:8.1
